---
main:
  - name: Accueil
    url: /
    weight: 10
  - name: Ã‰quipes
    url: /equipes/
    weight: 20
  - name: Histoire
    url: /histoire/
    weight: 30
  - name: Actualites
    url: /actualites/
    weight: 40
  - name: Contact
    url: /contact/
    weight: 50
